import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// New Markdown files from ds-changes appear without editing this file.
const sidebars: SidebarsConfig = {
  wikiSidebar: [{type: 'autogenerated', dirName: 'wiki'}],
  guideSidebar: [{type: 'autogenerated', dirName: 'guide'}],
};

export default sidebars;
